# The saved network list is attempted in networkId order for each round.
CHECK_INTERVAL_SEC=10
DISCONNECT_CONFIRMATIONS=2
MAX_ROUNDS=3
ATTEMPT_WAIT_SEC=15
ATTEMPT_POLL_SEC=3
HOTSPOT_RETRIES=3
HOTSPOT_RETRY_WAIT_SEC=5
